---
title: STAT 230 Homework 8
output: pdf_document
author: Ben Aoki-Sherwood
---

```{r, include = F}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(tidycensus)
library(ggResidpanel)
library(GGally)
library(car)
```

```{r}
get_plurality <- function(prop_dem, prop_rep, prop_other) {
  if (prop_dem > prop_rep & prop_dem > prop_other) {
    "democrat"
  } else if (prop_rep > prop_dem & prop_rep > prop_other) {
    "republican"
  } else {
    "other"
  }
}

elections <- read_csv("countypres_2000-2020.csv") %>%
  filter(year == 2020) 
elections2 <- elections %>%
  select(c(3,4,8,9,10)) %>%
  pivot_wider(id_cols = c(state_po, county_name, totalvotes), names_from = party, values_from = candidatevotes, values_fn = sum) %>%
  group_by(state_po, county_name) %>%
  replace_na(replace = list(OTHER = 0, GREEN = 0, LIBERTARIAN = 0)) %>%
  summarize(prop_dem = DEMOCRAT / totalvotes, 
            prop_rep = REPUBLICAN / totalvotes, 
            prop_other = (OTHER + GREEN + LIBERTARIAN) / totalvotes, 
            winning_party = get_plurality(prop_dem, prop_rep, prop_other)) %>%
  rename(state = state_po, county = county_name)
```


```{r}
col_spec = cols(
  "HCFC–22 Production from HFC–23 Destruction" = col_double(),
  "Lead Production" = col_double(),
  "Petroleum and Natural Gas Systems – LNG Storage" = col_double(),
  "Phosphoric Acid Production" = col_double(),
  "Silicon Carbide Production" = col_double(),
  "Titanium Dioxide Production" = col_double()
)
states <- rbind(data.frame(name = state.name, abb = state.abb), c(name = "Puerto Rico", abb = "PR"))
```

```{r}
state_unit <- Vectorize(function(state) {
  if (state == "LA") {
    "parish"
  } else if (state == "PR") {
    "municipio"
  } else {
    "county"
  }
})

special_tracts <- c("hopewell city", "anchorage municipality", 
                    "aleutians west census area")

emissions <- read_csv("ghgp_data_2021.csv", skip=3, n_max = 6483, col_types = col_spec)
emissions <- emissions %>%
  drop_na(County) %>%
  rename_with(str_to_lower) %>%
  mutate(emissions.total = `total reported direct emissions`,
         industry.sector = `industry type (sectors)`,
         county = str_to_lower(county),
         county = ifelse((!str_detect(county, "county|municipio|parish") &
                          !(county %in% special_tracts)), paste(county, state_unit(state)), county)) %>%
  select(state, county, industry.sector, emissions.total)
```

get census data
```{r}
census_data <- get_acs(geography = "county", variables = c("B02001_001E", "B19001_001E","B02001_002E"), year=2021, geometry = F)
code_book <- rbind(c("B02001_001", "total_population"), c("B19001_001", "household_income"), c("B02001_002", "total_white_population"))
code_book <- as.data.frame(code_book)
colnames(code_book) <- c("variable", "var_name")
census_data <- left_join(census_data, code_book)

#format the data so there is a row for each census tract and column for every variable
acs_data <- maditr::dcast(census_data, NAME ~ var_name, 
                               value.var = "estimate", 
                               fun.aggregate = NULL) %>%
  rename(county = NAME) %>%
  separate(col = "county", into = c("county", "state"), sep = ", ") %>%
  left_join(states, by = c("state" = "name")) %>%
  mutate(state = abb, county = str_to_lower(county)) %>%
  select(-abb)

acs_data <- cbind(acs_data, acs_data$total_white_population/acs_data$total_population)
colnames(acs_data)[6] <- "prop_pop_white"
```


join data
```{r}
emissions.joined <- emissions %>% left_join(acs_data, by = c("state","county"))
head(emissions.joined)
```

```{r}
county.emissions <- emissions.joined %>%
  group_by(county, state) %>%
  summarize(emissions = sum(emissions.total),
            household_income = first(household_income),
            total_population = first(total_population),
            total_white_population = first(total_white_population),
            prop_pop_white = first(prop_pop_white))
```

```{r}
ggplot(county.emissions, aes(x = log(household_income), y = log1p(emissions), color = prop_pop_white)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x="Log Median Household Income", y="Log Total Emissions from GHGP-Compliant Facilities", color="Proportion White Population", title="Log emissions from large emitters vs. log median household income for US counties")
```

```{r}
emissions.lm <- lm(emissions ~ household_income + total_population + prop_pop_white, data = county.emissions)
summary(emissions.lm)
resid_xpanel(emissions.lm)
resid_panel(emissions.lm, plots=c("resid","qq"))
```

```{r}
log.emissions.lm <- lm(log(emissions+1) ~ log(household_income) + log(total_population) + prop_pop_white, data = county.emissions)
summary(log.emissions.lm)
resid_xpanel(log.emissions.lm)
resid_panel(log.emissions.lm, plots=c("resid","qq"))
```

```{r}
#ggpairs(county.emissions)
vif(log.emissions.lm)
```


